const Coaching = require('../../models/coaching')
const mongoose = require('mongoose')

// Heroku dev database
const databaseUrl = require('../../config').mongoUri
mongoose.connect(databaseUrl, {
	useNewUrlParser: true,
	// useCreateIndex: true,
	useUnifiedTopology: true
})

const addDays = days => {
	const newDate = new Date(new Date().setDate(new Date().getDate() + days)).setHours(new Date().getHours() + 2)
	return new Date(newDate)
}

const removeDays = days => {
	const newDate = new Date(new Date().setDate(new Date().getDate() - days)).setHours(new Date().getHours() + 2)
	return new Date(newDate)
}

const addHours = hours => {
	const newDate = new Date().setHours(new Date().getHours() + hours + 2)
	return new Date(newDate)
}

const getStartingTime = date => {
	const result = new Date(date).getHours()
	if(result === 0) {
		return 22
	}
	if (result === 1) {
		return 23
	}
	if (result === 2) {
		return 0
	}
	return result - 2
}

const coachings = [
    new Coaching({ "_id" : "60c2f2d4b1c86f0004de0caf", "level" : "allLevel", "equipment" : [  ], "focus" : [ "chest" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "ec3eee28-7084-adc4-288f-2d3568228307", "muxLivePlaybackId" : "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA", "muxReplayPlaybackId" : "https://stream.mux.com/JV02OAOdjPDoUVDI5oKyCNWnJEwHD8aXctq6nKPC5uyg.m3u8", "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "cs", "ic", "ni", "en", "he", "th", "st", "is", "li", "al", "ca", "ics", "nic", "eni", "hen", "the", "sth", "ist", "lis", "ali", "cal", "nics", "enic", "heni", "then", "sthe", "isth", "list", "alis", "cali", "enics", "henic", "theni", "sthen", "isthe", "listh", "alist", "calis", "henics", "thenic", "stheni", "isthen", "listhe", "alisth", "calist", "thenics", "sthenic", "istheni", "listhen", "alisthe", "calisth", "sthenics", "isthenic", "listheni", "alisthen", "calisthe", "isthenics", "listhenic", "alistheni", "calisthen", "listhenics", "alisthenic", "calistheni", "alisthenics", "calisthenic", "calisthenics" ], "title_fuzzy" : [ "ss", "es", "re", "pr", "xp", "ex", "ess", "res", "pre", "xpr", "exp", "ress", "pres", "xpre", "expr", "press", "xpres", "expre", "xpress", "expres", "express", "in", "mi", "0m", "20", "min", "0mi", "20m", "0min", "20mi", "20min", "st", "he", "ch", "est", "hes", "che", "hest", "ches", "chest", "express 20min chest" ], "title" : "Express 20min Chest", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "sport" : "calisthenics", "duration" : 20, "startingDate" : "2021-06-20T19:30:21.616+0000", "startingTime" : 19, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1623388875/VonageApp/jtgriedio6dml5qvnewb.jpg", "coachRating" : 4, "__v" : 0, "isReplayReady" : true, "price" : 0 }),
    new Coaching({ "_id" : "61c0f185f9212a0004affd57", "level" : "allLevel", "equipment" : [ "yogaMat" ], "focus" : [ "flexibility", "mind", "upperBody", "backFocus", "arms", "lowerBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/ZWYoqVNcrz5PIHqjzJTGNhD2hUcm00mGcWPf00vC6seeE.m3u8", "isReplayReady" : true, "numberOfViewers" : 2, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "246def3e-cab4-463c-b962-8a39f53f9da1", "ratio" : "portrait", "coachUserName_fuzzy" : [ "ce", "nc", "en", "re", "or", "lo", "fl", "nce", "enc", "ren", "ore", "lor", "flo", "ence", "renc", "oren", "lore", "flor", "rence", "orenc", "loren", "flore", "orence", "lorenc", "floren", "lorence", "florenc", "florence", "rs", "er", "ie", "pi", "ers", "ier", "pie", "iers", "pier", "piers", "florence piers" ], "sport_fuzzy" : [ "ga", "og", "yo", "oga", "yog", "yoga" ], "title_fuzzy" : [ "ce", "nc", "an", "ea", "se", "nce", "anc", "ean", "sea", "ance", "eanc", "sean", "eance", "seanc", "seance", "de", "ga", "og", "yo", "oga", "yog", "yoga", "ng", "in", "hi", "ch", "tc", "et", "re", "tr", "st", "ing", "hin", "chi", "tch", "etc", "ret", "tre", "str", "hing", "chin", "tchi", "etch", "retc", "tret", "stre", "ching", "tchin", "etchi", "retch", "tretc", "stret", "tching", "etchin", "retchi", "tretch", "stretc", "etching", "retchin", "tretchi", "stretch", "retching", "tretchin", "stretchi", "tretching", "stretchin", "stretching", "séance de yoga stretching" ], "title" : "séance de yoga stretching", "coachFirstName" : "florence ", "coachLastName" : "piers", "coachUserName" : "florence piers", "coachId" : "61c08f45f9212a0004affcba", "sport" : "yoga", "duration" : 15, "startingDate" : "2021-12-20T21:11:32.801+0000", "startingTime" : 10, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1640034685/VonageApp/zu5k6aduzmdwhhoynrda.jpg", "coachRating" : 5, "price" : 3, "__v" : 0, "coachingRating" : { "numberOfRatings" : 1, "rating" : 5 } }),
    new Coaching({ "_id" : "61d9ad6b941a270004d289b2", "coachingRating" : { "numberOfRatings" : 1, "rating" : 5 }, "level" : "allLevel", "equipment" : [ "yogaMat" ], "focus" : [ "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/OWGvXoSyKDznwEBKeXAkJZpqTQWiY9eODMf11mfmGWc.m3u8", "isReplayReady" : true, "numberOfViewers" : 2, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "e1cbbd29-840a-4b67-943d-7f32627cb5f0", "ratio" : "portrait", "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "os", "do", "bd", "ab", "dos", "bdo", "abd", "bdos", "abdo", "abdos", "0'", "30", "30'", "pilates abdos 30'" ], "title" : "pilates abdos 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "sport" : "pilates", "duration" : 30, "startingDate" : "2022-01-08T15:27:39.660+0000", "startingTime" : 4, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1641655523/VonageApp/dedb8dyoz4qzmyl5im9e.jpg", "coachRating" : 5, "price" : 0.99, "__v" : 0 }),
    new Coaching({ "_id" : "61e05ff634748e000435a188", "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "level" : "allLevel", "equipment" : [ "yogaMat" ], "focus" : [ "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/p1jBLvy00jSDAFh68LULhVQrPoJgcDa8RpRGNlSAyP6g.m3u8", "isReplayReady" : true, "numberOfViewers" : 1, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "e3b6b06c-3526-47e4-8c02-2678f110f45d", "ratio" : "portrait", "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "sport" : "pilates", "duration" : 29, "startingDate" : "2022-01-13T17:23:02.348+0000", "startingTime" : 6, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1642094530/VonageApp/hmggnj8bfo3wy8qxeelr.jpg", "coachRating" : 5, "price" : 0.99, "__v" : 0 }),
    new Coaching({ "_id" : "61e7da49f7fdd2b098018a2f", "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "pilates", "duration" : 28, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-01-19T09:30:48.771+0000", "startingTime" : 10, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1642583916/VonageApp/iifpenir1wceuvkqr2ys.jpg", "focus" : [ "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/6iE5qnndHUFFB3Ahy5bXzq8Tu2nQpj8syyRYfkiPbPo.m3u8", "isReplayReady" : true, "numberOfViewers" : 1, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "f6ce2afe-548f-40ca-8dfc-bea6937093d3", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "__v" : 0 }),
    new Coaching({ "_id" : "61fac20087ab8d7bbad8b0da", "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "pilates", "duration" : 28, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-02T17:40:16.236+0000", "startingTime" : 6, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1643823515/VonageApp/pckh8solow6kuq1upcv2.jpg", "focus" : [  ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/mm02vCAnf6RcW8pbbyFDGKiw81Nl9TUZ83GiAO2wn8LU.m3u8", "isReplayReady" : true, "numberOfViewers" : 1, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "426bb66a-f689-43f0-8416-f252669c8e19", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "__v" : 0 }),
    new Coaching({ "_id" : "61fce70554c162085f0605c4", "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "pilates", "duration" : 26, "level" : "intermediate", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-04T08:42:45.443+0000", "startingTime" : 9, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1643964106/VonageApp/tir6grn6x8gmzdarh6pb.jpg", "focus" : [ "lowerBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/eshyTU2cpkq5EsWBU915qOkJmzZEAeXSd3qgXx7kEsk.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "08430b1e-9062-478f-8bc6-8cb882a4ba03", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "__v" : 0 }),
    new Coaching({ "_id" : "6200d7b51beb3c38be844ab0", "title" : "prendre des pectoraux", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "coachRating" : null, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "weightTraining", "duration" : 33, "level" : "allLevel", "equipment" : [ "weights" ], "startingDate" : "2022-02-07T08:26:29.413+0000", "startingTime" : 9, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644222312/VonageApp/rh2wraz2kgp6gfieydwy.jpg", "focus" : [ "chest", "upperBody", "strength" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/mMOFjoFmv3Fa4dxiaXTsKKBDS7Wo00c4bNtD25nBT2KY.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "b2683155-2d9a-4cb4-b788-b8be3f6773dc", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "ng", "in", "ni", "ai", "ra", "tr", "tt", "ht", "gh", "ig", "ei", "we", "ing", "nin", "ini", "ain", "rai", "tra", "ttr", "htt", "ght", "igh", "eig", "wei", "ning", "inin", "aini", "rain", "trai", "ttra", "httr", "ghtt", "ight", "eigh", "weig", "ining", "ainin", "raini", "train", "ttrai", "httra", "ghttr", "ightt", "eight", "weigh", "aining", "rainin", "traini", "ttrain", "httrai", "ghttra", "ighttr", "eightt", "weight", "raining", "trainin", "ttraini", "httrain", "ghttrai", "ighttra", "eighttr", "weightt", "training", "ttrainin", "httraini", "ghttrain", "ighttrai", "eighttra", "weighttr", "ttraining", "httrainin", "ghttraini", "ighttrain", "eighttrai", "weighttra", "httraining", "ghttrainin", "ighttraini", "eighttrain", "weighttrai", "ghttraining", "ighttrainin", "eighttraini", "weighttrain", "ighttraining", "eighttrainin", "weighttraini", "eighttraining", "weighttrainin", "weighttraining" ], "title_fuzzy" : [ "re", "dr", "nd", "en", "pr", "dre", "ndr", "end", "ren", "pre", "ndre", "endr", "rend", "pren", "endre", "rendr", "prend", "rendre", "prendr", "prendre", "es", "de", "des", "ux", "au", "ra", "or", "to", "ct", "ec", "pe", "aux", "rau", "ora", "tor", "cto", "ect", "pec", "raux", "orau", "tora", "ctor", "ecto", "pect", "oraux", "torau", "ctora", "ector", "pecto", "toraux", "ctorau", "ectora", "pector", "ctoraux", "ectorau", "pectora", "ectoraux", "pectorau", "pectoraux", "prendre des pectoraux" ], "__v" : 0 }),
    new Coaching({ "_id" : "62010c7e1beb3c38be844acd", "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "pilates", "duration" : 28, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-07T12:11:41.845+0000", "startingTime" : 1, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644235843/VonageApp/zdagnbfhhdrsfrjsox0w.jpg", "focus" : [  ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/vkJpDk5iOlRwvh7a01VUQhR4S6YBOydoo29SYRRI79JU.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "861a8ffa-c792-403f-925a-9a245b54d409", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "__v" : 0 }),
    new Coaching({ "_id" : "620121872127ced0205284b4", "title" : "stretching 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "stretching", "duration" : 30, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-07T13:41:26.824+0000", "startingTime" : 2, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644241258/VonageApp/v6e7fbfy02rmc64wtpm2.jpg", "focus" : [  ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/ijDpwnJe4VF02ZflfWzwc1bpLm4t4HYOdRMrN029NmRaA.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "0f63ac10-8684-4e28-9d1a-1d961915db0f", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "ng", "in", "hi", "ch", "tc", "et", "re", "tr", "st", "ing", "hin", "chi", "tch", "etc", "ret", "tre", "str", "hing", "chin", "tchi", "etch", "retc", "tret", "stre", "ching", "tchin", "etchi", "retch", "tretc", "stret", "tching", "etchin", "retchi", "tretch", "stretc", "etching", "retchin", "tretchi", "stretch", "retching", "tretchin", "stretchi", "tretching", "stretchin", "stretching" ], "title_fuzzy" : [ "ng", "in", "hi", "ch", "tc", "et", "re", "tr", "st", "ing", "hin", "chi", "tch", "etc", "ret", "tre", "str", "hing", "chin", "tchi", "etch", "retc", "tret", "stre", "ching", "tchin", "etchi", "retch", "tretc", "stret", "tching", "etchin", "retchi", "tretch", "stretc", "etching", "retchin", "tretchi", "stretch", "retching", "tretchin", "stretchi", "tretching", "stretchin", "stretching", "0'", "30", "30'", "stretching 30'" ], "__v" : 0 }),
    new Coaching({ "_id" : "620122e82127ced0205284b8", "title" : "prendre du dos", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "coachRating" : null, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "weightTraining", "duration" : 34, "level" : "allLevel", "equipment" : [ "weights" ], "startingDate" : "2022-02-07T13:47:18.119+0000", "startingTime" : 2, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644241588/VonageApp/o8enkqsqycmsrgid3ua2.jpg", "focus" : [ "backFocus", "arms", "upperBody", "strength" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/N3TBEuOca01pf8zHiIj13yHPnkPhFJamKt0001F88sECzg.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "334a37cd-4197-49d4-85e9-27de72998fb8", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "ng", "in", "ni", "ai", "ra", "tr", "tt", "ht", "gh", "ig", "ei", "we", "ing", "nin", "ini", "ain", "rai", "tra", "ttr", "htt", "ght", "igh", "eig", "wei", "ning", "inin", "aini", "rain", "trai", "ttra", "httr", "ghtt", "ight", "eigh", "weig", "ining", "ainin", "raini", "train", "ttrai", "httra", "ghttr", "ightt", "eight", "weigh", "aining", "rainin", "traini", "ttrain", "httrai", "ghttra", "ighttr", "eightt", "weight", "raining", "trainin", "ttraini", "httrain", "ghttrai", "ighttra", "eighttr", "weightt", "training", "ttrainin", "httraini", "ghttrain", "ighttrai", "eighttra", "weighttr", "ttraining", "httrainin", "ghttraini", "ighttrain", "eighttrai", "weighttra", "httraining", "ghttrainin", "ighttraini", "eighttrain", "weighttrai", "ghttraining", "ighttrainin", "eighttraini", "weighttrain", "ighttraining", "eighttrainin", "weighttraini", "eighttraining", "weighttrainin", "weighttraining" ], "title_fuzzy" : [ "re", "dr", "nd", "en", "pr", "dre", "ndr", "end", "ren", "pre", "ndre", "endr", "rend", "pren", "endre", "rendr", "prend", "rendre", "prendr", "prendre", "du", "os", "do", "dos", "prendre du dos" ], "__v" : 0 }),
    new Coaching({ "_id" : "62012e722127ced0205284bf", "title" : "stretching 1h", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "stretching", "duration" : null, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-07T14:36:34.006+0000", "startingTime" : 3, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644244507/VonageApp/glkgw8c2htchwd7l5nsv.jpg", "focus" : [  ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "05344cd5-9d96-4518-b46c-c3cc39194e23", "ratio" : "portrait", "price" : 2.49, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "ng", "in", "hi", "ch", "tc", "et", "re", "tr", "st", "ing", "hin", "chi", "tch", "etc", "ret", "tre", "str", "hing", "chin", "tchi", "etch", "retc", "tret", "stre", "ching", "tchin", "etchi", "retch", "tretc", "stret", "tching", "etchin", "retchi", "tretch", "stretc", "etching", "retchin", "tretchi", "stretch", "retching", "tretchin", "stretchi", "tretching", "stretchin", "stretching" ], "title_fuzzy" : [ "ng", "in", "hi", "ch", "tc", "et", "re", "tr", "st", "ing", "hin", "chi", "tch", "etc", "ret", "tre", "str", "hing", "chin", "tchi", "etch", "retc", "tret", "stre", "ching", "tchin", "etchi", "retch", "tretc", "stret", "tching", "etchin", "retchi", "tretch", "stretc", "etching", "retchin", "tretchi", "stretch", "retching", "tretchin", "stretchi", "tretching", "stretchin", "stretching", "1h", "stretching 1h" ], "__v" : 0 }),
    new Coaching({ "_id" : "620137b12127ced0205284ca", "title" : "full body hiit", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "coachRating" : null, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "circuitTraining", "duration" : 30, "level" : "allLevel", "equipment" : [  ], "startingDate" : "2022-02-07T15:16:01.053+0000", "startingTime" : 4, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644246916/VonageApp/lq39bifcs8byyqymbcjv.jpg", "focus" : [ "cardio", "lowerBody", "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/lKrWajDujWchUkj2zg7zDP00K6u9QKD00xVnH0035ffs74.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "951ac1a5-fb03-48c8-9713-0c9bd32ec16b", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "ng", "in", "ni", "ai", "ra", "tr", "tt", "it", "ui", "cu", "rc", "ir", "ci", "ing", "nin", "ini", "ain", "rai", "tra", "ttr", "itt", "uit", "cui", "rcu", "irc", "cir", "ning", "inin", "aini", "rain", "trai", "ttra", "ittr", "uitt", "cuit", "rcui", "ircu", "circ", "ining", "ainin", "raini", "train", "ttrai", "ittra", "uittr", "cuitt", "rcuit", "ircui", "circu", "aining", "rainin", "traini", "ttrain", "ittrai", "uittra", "cuittr", "rcuitt", "ircuit", "circui", "raining", "trainin", "ttraini", "ittrain", "uittrai", "cuittra", "rcuittr", "ircuitt", "circuit", "training", "ttrainin", "ittraini", "uittrain", "cuittrai", "rcuittra", "ircuittr", "circuitt", "ttraining", "ittrainin", "uittraini", "cuittrain", "rcuittrai", "ircuittra", "circuittr", "ittraining", "uittrainin", "cuittraini", "rcuittrain", "ircuittrai", "circuittra", "uittraining", "cuittrainin", "rcuittraini", "ircuittrain", "circuittrai", "cuittraining", "rcuittrainin", "ircuittraini", "circuittrain", "rcuittraining", "ircuittrainin", "circuittraini", "ircuittraining", "circuittrainin", "circuittraining" ], "title_fuzzy" : [ "ll", "ul", "fu", "ull", "ful", "full", "dy", "od", "bo", "ody", "bod", "body", "it", "ii", "hi", "iit", "hii", "hiit", "full body hiit" ], "__v" : 0 }),
    new Coaching({ "_id" : "620148ec2127ced0205284d5", "title" : "full body hiit", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "coachRating" : null, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "circuitTraining", "duration" : 30, "level" : "allLevel", "equipment" : [  ], "startingDate" : "2022-02-07T16:29:32.320+0000", "startingTime" : 5, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644251325/VonageApp/z9292pwpfjrakaapzazf.jpg", "focus" : [ "cardio", "lowerBody", "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/w01LHzDrscx02zr00P7j00SAjDPmQfp1o9iSzMQ01aynmxO8.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "af4127ed-14b5-4546-ae7d-7df75f79b65d", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "ng", "in", "ni", "ai", "ra", "tr", "tt", "it", "ui", "cu", "rc", "ir", "ci", "ing", "nin", "ini", "ain", "rai", "tra", "ttr", "itt", "uit", "cui", "rcu", "irc", "cir", "ning", "inin", "aini", "rain", "trai", "ttra", "ittr", "uitt", "cuit", "rcui", "ircu", "circ", "ining", "ainin", "raini", "train", "ttrai", "ittra", "uittr", "cuitt", "rcuit", "ircui", "circu", "aining", "rainin", "traini", "ttrain", "ittrai", "uittra", "cuittr", "rcuitt", "ircuit", "circui", "raining", "trainin", "ttraini", "ittrain", "uittrai", "cuittra", "rcuittr", "ircuitt", "circuit", "training", "ttrainin", "ittraini", "uittrain", "cuittrai", "rcuittra", "ircuittr", "circuitt", "ttraining", "ittrainin", "uittraini", "cuittrain", "rcuittrai", "ircuittra", "circuittr", "ittraining", "uittrainin", "cuittraini", "rcuittrain", "ircuittrai", "circuittra", "uittraining", "cuittrainin", "rcuittraini", "ircuittrain", "circuittrai", "cuittraining", "rcuittrainin", "ircuittraini", "circuittrain", "rcuittraining", "ircuittrainin", "circuittraini", "ircuittraining", "circuittrainin", "circuittraining" ], "title_fuzzy" : [ "ll", "ul", "fu", "ull", "ful", "full", "dy", "od", "bo", "ody", "bod", "body", "it", "ii", "hi", "iit", "hii", "hiit", "full body hiit" ], "__v" : 0 }),
    new Coaching({ "_id" : "620167832127ced0205284e7", "title" : "full body hiit", "coachFirstName" : "adrien", "coachLastName" : "floor", "coachUserName" : "adrien floor", "coachId" : "5f412f4bdff0cd00046a07ce", "coachRating" : null, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "circuitTraining", "duration" : 30, "level" : "allLevel", "equipment" : [  ], "startingDate" : "2022-02-07T18:40:03.092+0000", "startingTime" : 7, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644256894/VonageApp/skzoiy8ff3hbyf7ejomz.jpg", "focus" : [ "cardio", "lowerBody", "upperBody", "endurance" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/G5EuU7vJsNR5jKBcrG2wKpxytIlGHWL3lOSx4PgHf02w.m3u8", "isReplayReady" : true, "numberOfViewers" : 2, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "722de29f-570e-4900-8588-a03103d5ea73", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "en", "ie", "ri", "dr", "ad", "ien", "rie", "dri", "adr", "rien", "drie", "adri", "drien", "adrie", "adrien", "or", "oo", "lo", "fl", "oor", "loo", "flo", "loor", "floo", "floor", "adrien floor" ], "sport_fuzzy" : [ "ng", "in", "ni", "ai", "ra", "tr", "tt", "it", "ui", "cu", "rc", "ir", "ci", "ing", "nin", "ini", "ain", "rai", "tra", "ttr", "itt", "uit", "cui", "rcu", "irc", "cir", "ning", "inin", "aini", "rain", "trai", "ttra", "ittr", "uitt", "cuit", "rcui", "ircu", "circ", "ining", "ainin", "raini", "train", "ttrai", "ittra", "uittr", "cuitt", "rcuit", "ircui", "circu", "aining", "rainin", "traini", "ttrain", "ittrai", "uittra", "cuittr", "rcuitt", "ircuit", "circui", "raining", "trainin", "ttraini", "ittrain", "uittrai", "cuittra", "rcuittr", "ircuitt", "circuit", "training", "ttrainin", "ittraini", "uittrain", "cuittrai", "rcuittra", "ircuittr", "circuitt", "ttraining", "ittrainin", "uittraini", "cuittrain", "rcuittrai", "ircuittra", "circuittr", "ittraining", "uittrainin", "cuittraini", "rcuittrain", "ircuittrai", "circuittra", "uittraining", "cuittrainin", "rcuittraini", "ircuittrain", "circuittrai", "cuittraining", "rcuittrainin", "ircuittraini", "circuittrain", "rcuittraining", "ircuittrainin", "circuittraini", "ircuittraining", "circuittrainin", "circuittraining" ], "title_fuzzy" : [ "ll", "ul", "fu", "ull", "ful", "full", "dy", "od", "bo", "ody", "bod", "body", "it", "ii", "hi", "iit", "hii", "hiit", "full body hiit" ], "__v" : 0 }),
    new Coaching({ "_id" : "62054207151ad49522f602ad", "title" : "pilates 30'", "coachFirstName" : "estérelle", "coachLastName" : "martin", "coachUserName" : "estérelle", "coachId" : "61d9a9da941a270004d289a7", "coachRating" : 5, "coachingRating" : { "rating" : null, "numberOfRatings" : 0 }, "sport" : "pilates", "duration" : 29, "level" : "allLevel", "equipment" : [ "yogaMat" ], "startingDate" : "2022-02-10T16:49:11.090+0000", "startingTime" : 5, "pictureUri" : "https://res.cloudinary.com/dho1rqbwk/image/upload/v1644511606/VonageApp/wleit2f1rtsjqdekwypn.jpg", "focus" : [ "backFocus", "upperBody" ], "coachingLanguage" : "french", "freeAccess" : false, "muxStreamKey" : "", "muxLivePlaybackId" : "", "muxReplayPlaybackId" : "https://stream.mux.com/E3tefJo008Jajt85dc3dfZWXwjTA52kHu8U8jPtoGz3o.m3u8", "isReplayReady" : true, "numberOfViewers" : 0, "isLive" : false, "isLiveOver" : true, "livePayers" : 0, "replayPayers" : 0, "passthrough" : "993d2f72-5ef4-4484-ad88-6856017b5e76", "ratio" : "portrait", "price" : 0.99, "coachUserName_fuzzy" : [ "le", "ll", "el", "re", "er", "te", "st", "es", "lle", "ell", "rel", "ere", "ter", "ste", "est", "elle", "rell", "erel", "tere", "ster", "este", "relle", "erell", "terel", "stere", "ester", "erelle", "terell", "sterel", "estere", "terelle", "sterell", "esterel", "sterelle", "esterell", "esterelle" ], "sport_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates" ], "title_fuzzy" : [ "es", "te", "at", "la", "il", "pi", "tes", "ate", "lat", "ila", "pil", "ates", "late", "ilat", "pila", "lates", "ilate", "pilat", "ilates", "pilate", "pilates", "0'", "30", "30'", "pilates 30'" ], "__v" : 0 })
]

let done = 0
for (let i = 0; i < coachings.length; i++) {
	console.log('***************    ', i, '    *******************')
	coachings[i].save((err, result) => {
		console.log('ERR:', err)
		console.log('RESULT:', result)
		done++
		if (done === coachings.length) {
			exit()
		}
	})
}

const exit = () => {
	mongoose.disconnect()
}