const Coaching = require('../../models/coaching')
const mongoose = require('mongoose')

// Heroku dev database
const databaseUrl = require('../../config').mongoUri
mongoose.connect(databaseUrl, {
	useNewUrlParser: true,
	// useCreateIndex: true,
	useUnifiedTopology: true
})

const addDays = days => {
	const newDate = new Date(new Date().setDate(new Date().getDate() + days)).setHours(new Date().getHours() + 2)
	return new Date(newDate)
}

const removeDays = days => {
	const newDate = new Date(new Date().setDate(new Date().getDate() - days)).setHours(new Date().getHours() + 2)
	return new Date(newDate)
}

const addHours = hours => {
	const newDate = new Date().setHours(new Date().getHours() + hours + 2)
	return new Date(newDate)
}

const getStartingTime = date => {
	const result = new Date(date).getHours()
	if(result === 0) {
		return 22
	}
	if (result === 1) {
		return 23
	}
	if (result === 2) {
		return 0
	}
	return result - 2
}

const coachings = [
	// KARINA KLOP
	new Coaching(
		{
			"_id": "5f4558a6deb03a000469f571",
			"price": 2.49,
			"coachRating": 5,
			"title": "Summer body",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "crossfit",
			"duration": 40,
			"level": "intermediate",
			"equipment": ["kettlebell"],
			// "startingDate": addHours(3),
			// "startingTime": getStartingTime(addHours(3)),
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "upperBody", "lowerBody", "strength"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4557eddeb03a000469f56f",
			"price": 2.49,
			"coachRating": 5,
			"title": "Legs killer",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "hiit",
			"duration": 40,
			"level": "allLevel",
			"equipment": ["kettlebell"],
			"startingDate": removeDays(6),
			"startingTime": getStartingTime(removeDays(6)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"focus": ["lowerBody"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a000469f56e",
			"price": 2.49,
			"coachRating": 5,
			"title": "Morning routine",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "circuitTraining",
			"duration": 40,
			"level": "allLevel",
			"equipment": ["none"],
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4558a6deb04a000469f571",
			"price": 2.49,
			"coachRating": 5,
			"title": "tabata cardio",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "beginner",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "cardio"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4558a6deb05a000469f571",
			"price": 2.49,
			"coachRating": 5,
			"title": "Hell and back",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "allLevel",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(4),
			"startingTime": getStartingTime(removeDays(4)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "cardio"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4558a6deb06a000469f571",
			"price": 2.49,
			"coachRating": 5,
			"title": "Vo2 training",
			"coachFirstName": "Karina",
			"coachLastName": "Klop",
			"coachUserName": "Karina Klop",
			"coachId": "5f4427e06cc26300049d666b",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "allLevel",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(2),
			"startingTime": getStartingTime(removeDays(2)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "cardio"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	// JIMMY Ducan
	new Coaching(
		{
			"_id": "5f456564deb03a000469f573",
			"price": 2.49,
			"coachRating": 4,
			"title": "FTP builder",
			"coachFirstName": "Jimmy",
			"coachLastName": "Ducan",
			"coachUserName": "Jimmy Ducan",
			"coachId": "5f456523deb03a000469f572",
			"sport": "cycling",
			"duration": 40,
			"level": "beginner",
			"equipment": ["homeTrainer"],
			"startingDate": removeDays(2),
			"startingTime": getStartingTime(removeDays(2)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147867/VonageApp/coachingCatalog/workout-713658_1920_q0rxi9.jpg",
			"coachingLanguage": "english",
			"focus": ["cardio", "lowerBody"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f456609deb03a000469f574",
			"price": 2.49,
			"coachRating": 4,
			"title": "Lowerbody strength",
			"coachFirstName": "Jimmy",
			"coachLastName": "Ducan",
			"coachUserName": "Jimmy Ducan",
			"coachId": "5f456523deb03a000469f572",
			"sport": "weightlifting",
			"duration": 40,
			"level": "intermediate",
			"equipment": ["weights"],
			"startingDate": removeDays(5),
			"startingTime": getStartingTime(removeDays(5)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147993/VonageApp/coachingCatalog/pexels-victor-freitas-2261477_igkhvr.jpg",
			"coachingLanguage": "english",
			"focus": [],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f456609deb03a000469f521",
			"price": 2.49,
			"coachRating": 4,
			"title": "Destroyer",
			"coachFirstName": "Jimmy",
			"coachLastName": "Ducan",
			"coachUserName": "Jimmy Ducan",
			"coachId": "5f456523deb03a000469f572",
			"sport": "crossfit",
			"duration": 40,
			"level": "intermediate",
			"equipment": ["kettlebell"],
			"startingDate": removeDays(7),
			"startingTime": getStartingTime(removeDays(7)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147965/VonageApp/coachingCatalog/pexels-cottonbro-4761381_qaqicx.jpg",
			"coachingLanguage": "english",
			"focus": ["cardio"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45665ddeb03a000469f575",
			"price": 2.49,
			"coachRating": 4,
			"title": "Recovery run",
			"coachFirstName": "Jimmy",
			"coachLastName": "Ducan",
			"coachUserName": "Jimmy Ducan",
			"coachId": "5f456523deb03a000469f572",
			"sport": "running",
			"duration": 40,
			"level": "beginner",
			"equipment": ["treadMill"],
			"startingDate": removeDays(1),
			"startingTime": getStartingTime(removeDays(1)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147912/VonageApp/coachingCatalog/pexels-li-sun-2294361_eigeaf.jpg",
			"coachingLanguage": "english",
			"focus": ["cardio", "lowerBody"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "4f456609deb03a000469f574",
			"price": 2.49,
			"coachRating": 4,
			"title": "Abs igniter",
			"coachFirstName": "Jimmy",
			"coachLastName": "Ducan",
			"coachUserName": "Jimmy Ducan",
			"coachId": "5f456523deb03a000469f572",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "beginner",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147782/VonageApp/coachingCatalog/pexels-cottonbro-4761353_gucszu.jpg",
			"coachingLanguage": "english",
			"focus": ["core"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	// KAMILLA LOU
	new Coaching(
		{
			"_id": "5f456d3cdeb03a000469f577",
			"price": 0,
			"coachRating": 3,
			"title": "Inner peace",
			"coachFirstName": "Kamilla",
			"coachLastName": "Lou",
			"coachUserName": "Kamilla Lou",
			"coachId": "5f456b93deb03a000469f576",
			"sport": "meditation",
			"duration": 10,
			"level": "beginner",
			"equipment": ["none"],
			"startingDate": removeDays(2),
			"startingTime": getStartingTime(removeDays(2)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147988/VonageApp/coachingCatalog/wesley-tingey-57wo9F-r2-A-unsplash_vqvkg2.jpg",
			"coachingLanguage": "english",
			"focus": ["mind"],
			"freeAccess": true,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f456d87deb03a000469f578",
			"price": 0,
			"coachRating": 3,
			"title": "Pilate",
			"coachFirstName": "Kamilla",
			"coachLastName": "Lou",
			"coachUserName": "Kamilla Lou",
			"coachId": "5f456b93deb03a000469f576",
			"sport": "yoga",
			"duration": 30,
			"level": "allLevel",
			"equipment": ["none"],
			"startingDate": removeDays(1),
			"startingTime": getStartingTime(removeDays(1)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147855/VonageApp/coachingCatalog/pexels-taco-fleur-2780318_zqnmzh.jpg",
			"coachingLanguage": "english",
			"focus": ["core", "flexibility", "upperBody", "lowerBody"],
			"freeAccess": true,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f456dbadeb03a000469f579",
			"price": 2.49,
			"coachRating": 3,
			"title": "Easy run",
			"coachFirstName": "Kamilla",
			"coachLastName": "Lou",
			"coachUserName": "Kamilla Lou",
			"coachId": "5f456b93deb03a000469f576",
			"sport": "running",
			"duration": 50,
			"level":"beginner",
			"equipment": ["treadMill"],
			"startingDate": removeDays(30),
			"startingTime": getStartingTime(removeDays(30)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147855/VonageApp/coachingCatalog/pexels-taco-fleur-2780318_zqnmzh.jpg",
			"coachingLanguage": "french",
			"focus": ["cardio"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "3f456609deb03a000469f574",
			"price": 2.49,
			"coachRating": 3,
			"title": "Abs all the way",
			"coachFirstName": "Kamilla",
			"coachLastName": "Lou",
			"coachUserName": "Kamilla Lou",
			"coachId": "5f456b93deb03a000469f576",
			"sport": "hiit",
			"duration": 30,
			"level": "beginner",
			"equipment": ["yogaMat"],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(15),
			"startingTime": getStartingTime(removeDays(30)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147798/VonageApp/coachingCatalog/jonathan-borba-zfPOelmDc-M-unsplash_rjesuf.jpg",
			"coachingLanguage": "french",
			"focus": ["core"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "2f456609deb03a000469f574",
			"price": 2.49,
			"coachRating": 3,
			"title": "Abs and core",
			"coachFirstName": "Kamilla",
			"coachLastName": "Lou",
			"coachUserName": "Kamilla Lou",
			"coachId": "5f456b93deb03a000469f576",
			"sport": "hiit",
			"duration": 30,
			"level": "beginner",
			"equipment": ["yogaMat"],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(7),
			"startingTime": getStartingTime(removeDays(7)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147782/VonageApp/coachingCatalog/pexels-cottonbro-4761353_gucszu.jpg",
			"coachingLanguage": "french",
			"focus": ["core"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	// ADRIEN FLOOR
	new Coaching(
		{
			"_id": "5f45578bdeb03a000476f56e",
			"price": 0,
			"coachRating": 5,
			"title": "Waking up routine",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 40,
			"level": "allLevel",
			"equipment": ["none"],
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": true,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a000416f56e",
			"price": 0,
			"coachRating": 5,
			"title": "Intense core",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "hiit",
			"duration": 40,
			"level": "allLevel",
			"equipment": ["none"],
			"startingDate": removeDays(7),
			"startingTime": getStartingTime(removeDays(7)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": true,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f42278bdeb03a000476f56e",
			"price": 0,
			"coachRating": 5,
			"title": "Push and pull",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "hiit",
			"duration": 30,
			"level": "allLevel",
			"equipment": ["pullUpBar"],
			"startingDate": removeDays(8),
			"startingTime": getStartingTime(removeDays(8)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147912/VonageApp/coachingCatalog/pexels-li-sun-2294361_eigeaf.jpg",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": true,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isLive": false,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4558a6deb04a000469f531",
			"price": 2.49,
			"coachRating": 5,
			"title": "Building cardio",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "beginner",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(3),
			"startingTime": getStartingTime(removeDays(3)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1598380814/VonageApp/coachesAvatar/crossfit.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "cardio"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f4558a6deb04a000469f511",
			"price": 2.49,
			"coachRating": 5,
			"title": "Death by burpees",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 30,
			"level": "beginner",
			"equipment": [],
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"startingDate": removeDays(5),
			"startingTime": getStartingTime(removeDays(5)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147965/VonageApp/coachingCatalog/pexels-cottonbro-4761381_qaqicx.jpg",
			"coachingLanguage": "english",
			"freeAccess": false,
			"focus": ["core", "cardio"],
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "60aa8be963c68e00044124b7",
			"price": 2.49,
			"level": "allLevel",
			"equipment": [],
			"focus": [],
			"coachingLanguage": "english",
			"freeAccess": false,
			"muxStreamKey": "26e169c2-abac-370b-0deb-bc12ed3770d9",
			"muxLivePlaybackId": "https://stream.mux.com/yaOtcayqNuWQthmDSCLmQoXE2T6KLPDWJtwkFLfdR00g",
			"muxReplayPlaybackId": "https://stream.mux.com/pplHWsWyz2FcFsVyHJ9dnjqI5uUjVpqTrDPBFccOPV4.m3u8",
			"isReplayReady": true,
			"isLive": false,
			"isLiveOver": true,
			"title": "hiit",
			"coachFirstName": "adrien",
			"coachLastName": "floor",
			"coachUserName": "adrien floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": null,
			"startingDate": removeDays(6),
			"startingTime": getStartingTime(removeDays(6)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1621789064/VonageApp/jlenjsna7mkjbbshw4b4.jpg",
			"coachRating": 4,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "60aa8be963c68e00044124c3",
			"price": 2.49,
			"level": "intermediate",
			"equipment": [],
			"focus": [],
			"coachingLanguage": "french",
			"freeAccess": false,
			"muxStreamKey": "26e169c2-abac-370b-0deb-bc12ed3770d9",
			"muxLivePlaybackId": "https://stream.mux.com/yaOtcayqNuWQthmDSCLmQoXE2T6KLPDWJtwkFLfdR00g",
			"muxReplayPlaybackId": "https://stream.mux.com/NXB00O7G6qO4DHFTf974H6b74cCC8phwY86TT5qJzgKQ.m3u8",
			"isReplayReady": true,
			"isLive": false,
			"isLiveOver": true,
			"title": "Super Cardio 30",
			"coachFirstName": "adrien",
			"coachLastName": "floor",
			"coachUserName": "adrien floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": null,
			"startingDate": removeDays(1),
			"startingTime": getStartingTime(removeDays(1)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1622802703/VonageApp/zikrkovnqyzhb0emjodg.jpg",
			"coachRating": 4,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "60aa8be963c68e00044124c4",
			"price": 2.49,
			"level": "allLevel",
			"equipment": [],
			"focus": [],
			"coachingLanguage": "french",
			"freeAccess": false,
			"muxStreamKey": "26e169c2-abac-370b-0deb-bc12ed3770d9",
			"muxLivePlaybackId": "https://stream.mux.com/yaOtcayqNuWQthmDSCLmQoXE2T6KLPDWJtwkFLfdR00g",
			"muxReplayPlaybackId": "https://stream.mux.com/e2dcB6eIK12yz4eHAjQGrnfQXNeMcSuH4vGTU00dyvHM.m3u8",
			"isReplayReady": true,
			"isLive": false,
			"isLiveOver": true,
			"title": "Express 20min Legs",
			"coachFirstName": "adrien",
			"coachLastName": "floor",
			"coachUserName": "adrien floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": null,
			"startingDate": removeDays(2),
			"startingTime": getStartingTime(removeDays(2)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1622632699/VonageApp/ppkivhpgjj6tiueytujg.jpg",
			"coachRating": 4,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "60c2f2d4b1c86f0004de0caf",
			"level": "allLevel",
			"equipment": [],
			"focus": ["chest"],
			"coachingLanguage": "french",
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"muxReplayPlaybackId": "https://stream.mux.com/JV02OAOdjPDoUVDI5oKyCNWnJEwHD8aXctq6nKPC5uyg.m3u8",
			"isReplayReady": true,
			"isLive": false,
			"isLiveOver": true,
			"title": "Express 20min Chest",
			"coachFirstName": "adrien",
			"coachLastName": "floor",
			"coachUserName": "adrien floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "calisthenics",
			"duration": 20,
			"startingDate": removeDays(2),
			"startingTime": getStartingTime(removeDays(2)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1623388875/VonageApp/jtgriedio6dml5qvnewb.jpg",
			"coachRating": 4,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a060476f56e",
			"price": 2.49,
			"coachRating": 5,
			"title": "10 jours core challenge 1",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(90),
			"startingTime": getStartingTime(removeDays(90)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a010576f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 2",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(89),
			"startingTime": getStartingTime(removeDays(89)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a090476f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 3",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(88),
			"startingTime": getStartingTime(removeDays(88)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a080476f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 4",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(87),
			"startingTime": getStartingTime(removeDays(87)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a070476f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 5",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(86),
			"startingTime": getStartingTime(removeDays(86)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a060476f66e",
			"coachRating": 5,
			"title": "10 jours core challenge 6",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(85),
			"startingTime": getStartingTime(removeDays(85)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a050476f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 7",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(84),
			"startingTime": getStartingTime(removeDays(84)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a040476f56e",
			"coachRating": 5,
			"title": "10 jours core challenge 8",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(83),
			"startingTime": getStartingTime(removeDays(83)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"price": 2.49,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a030476f56e",
			"price": 2.49,
			"coachRating": 5,
			"title": "10 jours core challenge 9",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(82),
			"startingTime": getStartingTime(removeDays(82)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	),
	new Coaching(
		{
			"_id": "5f45578bdeb03a020476f56e",
			"price": 2.49,
			"coachRating": 5,
			"title": "10 jours core challenge 10",
			"coachFirstName": "Adrien",
			"coachLastName": "Floor",
			"coachUserName": "Adrien Floor",
			"coachId": "5f412f4bdff0cd00046a07ce",
			"sport": "circuitTraining",
			"duration": 20,
			"level": "allLevel",
			"equipment": ["yogaMat"],
			"startingDate": removeDays(81),
			"startingTime": getStartingTime(removeDays(81)),
			"pictureUri": "https://res.cloudinary.com/dho1rqbwk/image/upload/v1602147955/VonageApp/coachingCatalog/StockSnap_TIHQMAG3KH_iq3vqv.jpg",
			"muxReplayPlaybackId": "https://stream.mux.com/uiixZ8ucm2da5dIsUbp15X6HUXc8YuM11022gE028EjIY.m3u8",
			"isReplayReady": true,
			"muxStreamKey": "ec3eee28-7084-adc4-288f-2d3568228307",
			"muxLivePlaybackId": "https://stream.mux.com/kGg8uAYdDDn501901AmP5wQyfcgGDOEAMlt9AtZnc9XUA",
			"coachingLanguage": "english",
			"focus": ["core", "cardio", "flexibility"],
			"freeAccess": false,
			"muxStreamKey": "",
			"muxLivePlaybackId": "",
			"isLive": false,
			"isLiveOver": true,
			"__v": 0
		}
	)
]

let done = 0
for (let i = 0; i < coachings.length; i++) {
	console.log('***************    ', i, '    *******************')
	coachings[i].save((err, result) => {
		console.log('ERR:', err)
		console.log('RESULT:', result)
		done++
		if (done === coachings.length) {
			exit()
		}
	})
}

const exit = () => {
	mongoose.disconnect()
}